[package]
name = "group-finder-bot"
version = "0.1.0"
authors = ["orion78fr <orion78fr@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.102"
serde_json = "1.0.41"
chrono = "0.4.9"

[dependencies.serenity]
version = "0.7"
features = ["framework", "standard_framework"]